<!DOCTYPE html>
<html>
	<head>
		<title>Challenges</title>
		<meta charset="utf-8" />
		<meta name="description" content="Lorem ipsum" />
		<meta name="keywords" content="Lorem ipsum" />
		<link rel="stylesheet" href="/css/reset.css" />
		<link rel="stylesheet" href="/css/style.css" />
		<script src="/js/jquery-1.7.2.min.js" type="text/javascript"></script>
		<script src="/js/cufon/yui.js" type="text/javascript"></script>
		<script src="/js/cufon/font.js" type="text/javascript"></script>
		<script src="/js/cufon/config.js" type="text/javascript"></script>
	</head>
	<body>
		<header>
			<div class="login">
				<p>Witaj <span>nieznajomy!</span><a href="/">zaloguj się</a></p>
			</div>
			<h1><a href="/">Challenges</a></h1>
		</header>
		<div class="page-wrapper <?php echo $this->layout_Class()->getPageWrapper()?>">
			<?php echo $this->layout_FlashMessenger(); ?>
			<div class="content">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		<footer>
			<p>Copyfight &copy; 2012</p>
			<a href="#">kontakt</a>
			<a href="#">informacje</a>
		</footer>
	</body>
</html>