<h2 class="webfont">Logowanie</h2>
<div>
	<form method="post" action="/">

		<?php $sField = 'email';
		echo $this->form_Field(
			'email',
			$sField,
			$this->formText($sField, $this->form_Value($sField))
		)?>

		<?php $sField = 'passwd';
		echo $this->form_Field(
			'hasło',
			$sField,
			$this->formPassword($sField, $this->form_Value($sField))
		)?>

		<?php $sField = 'remember';
		echo $this->form_Field(
			'Zapamiętaj mnie',
			$sField,
			$this->formCheckbox($sField, $this->form_Value($sField)),
			array('class' => 'remember')
		)?>

		<button type="submit">zaloguj</button>
		<br /><br />
		<strong>Nie masz konta? </strong><a href="/register">zarejestruj się</a>
	</form>


</div>