<?php
	$this->layout_Class('list-wrapper task-list');
	$this->layout_Breadcrumbs(array(
		'moje rozwiązania'	=> null
	));
?>

<h2 class="webfont">Lista moich rozwiazan</h2>

<table>
	<thead>
		<tr>
			<td>Nazwa zadania</td>
			<td>Autor</td>
			<td>Czas wykonania</td>
			<td>Status</td>
			<td>Opis</td>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->oPaginator as $oSolution): ?>
		<tr>
			<td>
				<a href="/solutions/edit/id/<?php echo $oSolution->getId() ?>">
					<?php echo $oSolution->getTask()->getName() ?>
				</a>
			</td>
			<td><?php echo $oSolution->getAuthor()->getFullName() ?></td>
			<td><?php echo $oSolution->getRunTime() === null ? '---' : number_format($oSolution->getRunTime(), 0, ',', ' ') . ' ms' ?></td>
			<td>
				<?php switch($oSolution->getStatus()) {
						case \Model\Tasks\Solution::STATUS_NEW: echo 'oczekuje na ocenę'; break;
						case \Model\Tasks\Solution::STATUS_TESTING: echo 'w trakcie oceny'; break;
						case \Model\Tasks\Solution::STATUS_SUCCESS: echo 'sukces'; break;
						case \Model\Tasks\Solution::STATUS_ERROR: echo 'błąd'; break;
				}?>
			</td>
			<td><?php echo $oSolution->getInfo() ?></td>
		</tr>
<?php endforeach;?>
	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator, [
	'pname'		=> 'page',
	'pcount'	=> 6,
	'actionUrl'	=> '/solutions/my-list'
]);?>