<?php
	$this->layout_Class('task-show');
	$this->layout_Breadcrumbs(array(
		'moje zadania'		=> '/tasks/my-list',
		'zadanie'			=> '/tasks/my-show/id/'. $this->oSolution->getTask()->getId(),
		'lista rozwiazań'	=> '/solutions/list/id/'. $this->oSolution->getTask()->getId(),
		'rozwiązanie'		=> null
	));

	$aLanguages = \Model\Tasks\SolutionFactory::getLanguages();
?>
<h2 class="webfont">Rozwiazanie zadania</h2>

<div class="head">
	<h3><?php echo $this->oSolution->getTask()->getName()?></h3>
	<span></span>
</div>
<div class="desc">
	<label>Autor:</label>
	<p>
		<?php echo $this->oSolution->getAuthor()->getFullName() ?>
	</p>
</div>
<div class="desc">
	<label>Czas wykonania:</label>
	<p>
		<?php echo number_format($this->oSolution->getRunTime(), 0, ',', ' ') ?> ms
	</p>
</div>
<div class="desc">
	<label>Język programowania:</label>
	<p>
		<?php echo $aLanguages[$this->oSolution->getLanguage()] ?>
	</p>
</div>
<div class="desc">
	<label>Kod rozwiązania:</label>
	<p>
		<?php echo str_replace("\t", '&nbsp;&nbsp;&nbsp;&nbsp;', nl2br($this->oSolution->getCode())) ?>
	</p>
</div>
