<?php
	$bEdit = isset($this->oSolution);

	$this->layout_Class('standalone-form solution-show');

	if($bEdit)
	{
		$this->layout_Breadcrumbs(array(
			'moje rozwiązania'	=> '/solutions/my-list',
			'edycja zadania'	=> null
		));
	}
	else
	{
		$this->layout_Breadcrumbs(array(
			'moje rozwiązania'	=> '/solutions/my-list',
			'nowe rozwiązanie'	=> null
		));
	}

	$aEmpty = ['' => '-- wybierz z listy --']
?>



<?php if(isset($this->oSolution)):?>
	<h2 class="webfont">Edycja rozwiązania</h2>
<?php else:?>
	<h2 class="webfont">Dodawanie nowego rozwiązania</h2>
<?php endif;?>

<h2>Zadanie: <?php echo $this->oTask->getName() ?></h2>

<div class="desc">
	<label>Opis zadania</label>
	<p>
		<?php echo str_replace("\n", '<br />', $this->oTask->getDescription()) ?>
	</p>
</div>

<?php if($bEdit && $this->oSolution->getInfo() !== null): ?>
	<div class="desc">
		<label>Opis błędu</label>
		<p class="error"><?php echo $this->oSolution->getInfo() ?></p>
	</div>
<?php endif; ?>

<div class="desc">
	<label>Twoje rozwiązanie</label>
</div>
<form method="post" action="/solutions<?php echo $bEdit ? '/edit/id/'. $this->oSolution->getId() : '/add/id/'. $this->oTask->getId() ?>">
	<?php $sField = 'language';
	echo $this->form_Field(
		'język',
		$sField,
		$this->formSelect($sField, $this->form_Value($sField), null, $aEmpty + \Model\Tasks\SolutionFactory::getLanguages())
	)?>

	<?php $sField = 'code';
	echo $this->form_Field(
		'rozwiązanie',
		$sField,
		$this->formTextarea($sField, $this->form_Value($sField), array('cols' => 70, 'rows' => 5))
	)?>

	<button type="submit"><?php echo $bEdit ? 'zapisz' : 'dodaj'?></button>
</form>
