<?php
	$this->layout_Class('list-wrapper task-list');
	$this->layout_Breadcrumbs(array(
		'zadania'	=> null
	));
?>

<h2 class="webfont">Lista wszystkich zadan</h2>

<table>
	<thead>
		<tr>
			<td class="name">Nazwa zadania</td>
			<td class="author">Autor</td>
			<td class="desc">Opis zadania</td>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->oPaginator as $oTask): ?>
		<tr>
			<td>
				<a href="/tasks/show/id/<?php echo $oTask->getId() ?>">
					<?php echo $oTask->getName() ?>
				</a>
			</td>
			<td><?php echo $oTask->getAuthor()->getFullName() ?></td>
			<td><?php echo substr($oTask->getDescription(), 0, 120) ?>...</td>
		</tr>
<?php endforeach;?>
	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator, [
	'pname'		=> 'page',
	'pcount'	=> 6,
	'actionUrl'	=> '/tasks/list'
]);?>