<header>
	<h2>Lista wszystkich zadań</h2>
	<a href="/dashboard">strona główna</a> >
	<a href="/tasks/list">zadania</a>
</header>

<?php if(isset($this->oCurrentUser) && $this->oCurrentUser->getRole() == \Model\Users\User::ROLE_MOD): ?>
	<a href="/tasks/my-list">moje zadania</a>
	<br /><br />
<?php endif; ?>

<table>
	<thead>
		<tr>
			<td>Nazwa zadania</td>
			<td>Opis zadania</td>
			<td>Autor</td>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->oPaginator as $oTask): ?>
		<tr>
			<td>
				<a href="/tasks/show/id/<?php echo $oTask->getId() ?>">
					<?php echo $oTask->getName() ?>
				</a>
			</td>
			<td><?php echo substr($oTask->getDescription(), 0, 120) ?></td>
			<td><?php echo $oTask->getAuthor()->getFullName() ?></td>
		</tr>
<?php endforeach;?>
	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator, [
	'pname'		=> 'page',
	'pcount'	=> 6,
	'actionUrl'	=> '/tasks/my-list'
]);?>