<h1>Lista moich zadań</h1>

<a href="/tasks/list">wróć do listy wszystkich zadań</a> |
<a href="/tasks/add">dodaj nowe zadanie</a>
<br /><br />

<table>
	<thead>
		<tr>
			<td>Nazwa zadania</td>
			<td>Opis zadania</td>
			<td>Akcje</td>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->oPaginator as $oTask): ?>
		<tr>
			<td>
				<a href="/tasks/show/id/<?php echo $oTask->getId() ?>">
					<?php echo $oTask->getName() ?>
				</a>
			</td>
			<td><?php echo substr($oTask->getDescription(), 0, 120) ?></td>
			<td>
				<a href="/tasks/edit/id/<?php echo $oTask->getId() ?>">edytuj</a> |
				<a href="/tasks/del/id/<?php echo $oTask->getId() ?>">usuń</a>
			</td>
		</tr>
<?php endforeach;?>
	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator, [
	'pname'		=> 'page',
	'pcount'	=> 6,
	'actionUrl'	=> '/tasks/my-list'
]);?>