<?php
	$this->layout_Class('list-wrapper task-list tasks-my');
	$this->layout_Breadcrumbs(array(
		'moje zadania'	=> null
	));
?>
<h2 class="webfont">Lista moich zadan</h2>

<div class="head-actions">
	<a href="/tasks/add">dodaj nowe zadanie</a>
</div>

<table>
	<thead>
		<tr>
			<td class="name">Nazwa zadania</td>
			<td class="desc">Opis zadania</td>
			<td class="actions">Akcje</td>
		</tr>
	</thead>
	<tbody>
<?php foreach($this->oPaginator as $oTask): ?>
		<tr>
			<td>
				<a href="/tasks/show/id/<?php echo $oTask->getId() ?>">
					<?php echo $oTask->getName() ?>
				</a>
			</td>
			<td><?php echo substr($oTask->getDescription(), 0, 120) ?></td>
			<td>
				<a href="/tasks/edit/id/<?php echo $oTask->getId() ?>">edytuj</a> |
				<a href="#/tasks/del/id/<?php echo $oTask->getId() ?>" class="confirm" data-ask="Czy na pewno chcesz usunąć to zadanie?">usuń</a>
			</td>
		</tr>
<?php endforeach;?>
	</tbody>
</table>

<?php echo $this->paginator($this->oPaginator, [
	'pname'		=> 'page',
	'pcount'	=> 6,
	'actionUrl'	=> '/tasks/my-list'
]);?>