<?php
	$this->layout_Class('task-show');
	$this->layout_Breadcrumbs(array(
		'zadania'			=> '/tasks/list',
		'szczegóły zadania'	=> null
	));
?>

<h2 class="webfont">Szczegoly zadania</h2>

<div class="head">
	<h3><?php echo $this->oTask->getName() ?></h3>
<?php if(isset($this->oCurrentUser)): ?>
	<span>
		<a href="/solutions/add/id/<?php echo $this->oTask->getId()?>">zgłoś rozwiązanie</a>
	</span>
<?php endif; ?>
</div>
<div class="desc">
	<label>Opis zadania</label>
	<p>
		<?php echo str_replace("\n", '<br />', $this->oTask->getDescription()) ?>
	</p>
</div>
