<?php
	$bEdit = isset($this->oTask);

	$this->layout_Class('standalone-form');

	if($bEdit)
	{
		$this->layout_Breadcrumbs(array(
			'moje zadania'		=> '/tasks/my-list',
			'szczegóły zadania'	=> '/tasks/my-show/id/'. $this->oTask->getId(),
			'edycja zadania'	=> null
		));
	}
	else
	{
		$this->layout_Breadcrumbs(array(
			'moje zadania'	=> '/tasks/my-list',
			'nowe zadanie'	=> null
		));
	}


?>

<?php if(isset($this->oTask)):?>
	<h2 class="webfont">Edycja zadania</h2>
<?php else:?>
	<h2 class="webfont">Tworzenie nowego zadania</h2>
<?php endif;?>

<form method="post" action="/tasks<?php echo $bEdit ? '/edit/id/'. $this->oTask->getId() : '/add' ?>">
	<?php $sField = 'name';
	echo $this->form_Field(
		'nazwa zadania',
		$sField,
		$this->formText($sField, $this->form_Value($sField))
	)?>

	<?php $sField = 'description';
	echo $this->form_Field(
		'opis zadania',
		$sField,
		$this->formTextarea($sField, $this->form_Value($sField), array('cols' => 70, 'rows' => 5))
	)?>

	<?php $sField = 'input';
	echo $this->form_Field(
		'dane wejściowe',
		$sField,
		$this->formTextarea($sField, $this->form_Value($sField), array('cols' => 70, 'rows' => 5))
	)?>

	<?php $sField = 'output';
	echo $this->form_Field(
		'dane wyjściowe',
		$sField,
		$this->formTextarea($sField, $this->form_Value($sField), array('cols' => 70, 'rows' => 5))
	)?>


	<button type="submit"><?php echo $bEdit ? 'zapisz' : 'dodaj'?></button>
</form>